/* Modelagem */
/* ENTIDADE = TABELA */
/* CAMPOS = ATRIBUTOS */ 

CLIENTE

NOME - CARACTER(30)
CPF - NUMERICO(11)
EMAIL - CARACTER(30)       } /* campos */
TELEFONE - CARACTER(30)
ENDEREÇO - CARACTER(100)
SEXO - CARACTER(1)



/* PROCESSOS DE MODELAGEM */

MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM
MODELAGEM FÍSICA - 

/* MODELAGEM FISICA */

/* CRIANDO */

CREATE DATABASE PROJETO;

/* CONECTANDO AO BANCO */
USE PROJETO;

/* CRIANDO UMA TABELA */

CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);

/* VERIFICANDO AS TABLES */
SHOW TABLES;
USE PROJETO;

/* DESCOBRINDO ESTRUTURA DA TABELA */
DESC CLIENTE;

/* VAR CHAR varia do tamanho, char é unico */

/* inserindo na tabela, OMITINDO AS COLUNAS */
INSERT INTO CLIENTE VALUES('JOÃO', 'M', 'JOAOGMAIL.COM', 91821941, '1218991231', 'MAIA LACERDA - ESTACIO RIO DE JANEIRO RJ');

INSERT INTO CLIENTE(NOME,SEXO,EMAIL,CPF,TELEFONE,ENDERECO)VALUES('OTARIO', 'M', 'OTARIO@GMAIL.COM','3592385290', '94819121', 'Rua do krl rj');

/* COMANDO SELECT */

SELECT NOW() as DATA_HORA, 'Diogo Borges' as Vagabundo;

SELECT 'FELIPE MAFRA';

SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS */


SELECT NOME AS CLIENTE, SEXO, EMAIL, FROM CLIENTE;

SELECT EMAIL, SEXO, ENDERECO, NOME, FROM CLEINTE;

SELECT EMAIL, SEXO, ENDERECO, NOME, NOW() DATA_HORA FROM CLIENTE;


/* FILTROS WHERE-- */
SELECT NOME, SEXO, EMAIL, TELEFONE FROM CLIENTE
WHERE SEXO = 'F';

/*ACHANDO O MAIS PROX */
SELECT NOME, SEXO, EMAIL, TELEFONE FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';

/* PORCENTAGEM %, É UM DELIMITADOR, ANTES PEGA TUDO QUE VEM ANTES DA PALAVRA
APÓS, PEGA TUDO QUE VEM APÓS A PALAVRA, ENTRE (%RJ%), PEGA SÓ A PALAVRA */

/* CONTANDO REGRISTROS */

SELECT COUNT(*) FROM CLIENTE; /* CONTA E MOSTRA O NÚMERO DE PARAMETROS */

SELECT SEXO, COUNT(*)
FROM CLIENTE
GROUP BY SEXO; /* CONTANDO POR AGRUPAMENTO, (NÚMERO DE CLIENTES PELO SEXO) */

SELECT COUNT(*), departamento -- Conta odepartamento da tabela funcionarios, e agrupa pelo departamento
FROM funcionarios
GROUP by departamento
order by 1; -- coloca em ordem
-

SELECT COUNT(*), departamento
FROM funcionarios
where sexo = 'masculino'
GROUP by departamento;

SELECT COUNT(*), departamento
from funcionarios
where sexo = 'feminino'
group by departamento;


