1 --Todo campo vetorizado se torna uma tabela
		--Isto é, campos que tem mais de uma identificação, como se fosse uma lista, exemplo: Ka, fiesta, civic > Marcas
																						   -- Amarelo, azul, > Cores
																						   -- 91132-2932, 2919-9320 > telefones
	
	2--Todo campo multivalorado se torna outra tabela(quando o campor for divisível)
		--ex:(Oscar cury - bom retiro - patos de minas - mg), da pra ser dividido por
			--bairro, cidade, estado.....
	
	3-- toda tabela necessita de pelo menos um campo que identifique todo o registro como sendo unico
		-- Que é chamado de chave primária ou primary key. OU SEJA, toda tabela precisa de uma  key
			-- há dois tipos de chave, natural e artificial.
				--natural -cpf, rg(coisas unicas de cada pessoa)
				-- artificial - ID e etc..


CREATE DATABASE ExercIRB;
USE EXERCIRB;
CREATE TABLE CONTAS(
	NOME VARCHAR(40),
	IDNUMERO INT PRIMARY KEY,
	VALOR FLOAT(10,2),
	VENCIMENTO DATE
);

CREATE TABLE BANCOS(
	NOME VARCHAR(30),
	ID_REGISTROB INT PRIMARY KEY AUTO_INCREMENT,
	IDBANCO INT,
	ID_NUMERO INT
);

ALTER TABLE BANCOS
ADD CONSTRAINT FK_BANCO
FOREIGN KEY (ID_NUMERO)
REFERENCES CONTAS(IDNUMERO);

INSERT INTO CONTAS VALUES('ABC PAPELARIA', 100100, 5000.00, 20170120); 
INSERT INTO CONTAS VALUES('LIVRARIA FERNANDES', 100110, 2500.00 , 20170122); 
INSERT INTO CONTAS VALUES('LIVRARIA FERNANDES', 100120, 1500.00 ,120161015);
INSERT INTO CONTAS VALUES('ABC PAPELARIA' ,100130, 8000.00 , 20161015);
INSERT INTO CONTAS VALUES('LER E SABER', 200120, 10500.00 , 20180426); 
INSERT INTO CONTAS VALUES('LIVROS E CIA', 200125, 2000.00 , 20180426); 
INSERT INTO CONTAS VALUES('LER E SABER', 200130, 11000.00 , 20180926); 
INSERT INTO CONTAS VALUES('PAPELARIA SILVA', 250350, 1500.00 , 20180126);
INSERT INTO CONTAS VALUES('LIVROS MM', 250360, 500.00 , 20181218); 
INSERT INTO CONTAS VALUES('LIVROS MM', 250370, 3400.00 , 20180426);
INSERT INTO CONTAS VALUES('PAPELARIA SILVA', 250380, 3500.00 , 20180426); 
INSERT INTO CONTAS VALUES('LIVROS E CIA', 453360, 1500.00 , 20180615); 
INSERT INTO CONTAS VALUES('LIVROS MM', 453365, 5400.00 , 20180615);
INSERT INTO CONTAS VALUES('PAPELARIA SILVA', 453370, 2350.00 , 20171227); 
INSERT INTO CONTAS VALUES('LIVROS E CIA', 453380, 1550.00 ,20171227); 
INSERT INTO CONTAS VALUES('ABC PAPELARIA', 980130, 4000.00 , 20161211); 
INSERT INTO CONTAS VALUES('LIVRARIA FERNANDES', 770710, 2500.00  20161115); 
INSERT INTO CONTAS VALUES('ABC PAPELARIA', 985001, 3000.00 , 20160911); 
INSERT INTO CONTAS VALUES('PAPEL E AFINS', 985002, 2500.00 , 20160312); 
INSERT INTO CONTAS VALUES('LER E SABER', 888132, 2500.00 , 20170305);

INSERT INTO BANCOS VALUES('ITAU',NULL,1,100100);
INSERT INTO BANCOS VALUES('ITAU',NULL,1,100110);
INSERT INTO BANCOS VALUES('BRADESCO',NULL,2,100120);
INSERT INTO BANCOS VALUES('SANTANDER',NULL,3,100130);
INSERT INTO BANCOS VALUES('BANCO DO BRASIL',NULL,4,200120);
INSERT INTO BANCOS VALUES('BANCO DO BRANULL,SIL',NULL,4,200125);
INSERT INTO BANCOS VALUES('ITAU',NULL,1,200130);
INSERT INTO BANCOS VALUES('BRADESCO',NULL,2,250350);
INSERT INTO BANCOS VALUES('SANTANDER',NULL,3,250360);
INSERT INTO BANCOS VALUES('SANTANDER',NULL,3,250370);
INSERT INTO BANCOS VALUES('BANCO DO BRASIL',NULL,4,250380);
INSERT INTO BANCOS VALUES('ITAU',NULL,1,453360);
INSERT INTO BANCOS VALUES('BRADESCO',NULL,2,453365);
INSERT INTO BANCOS VALUES('ITAU',NULL,1,453370);
INSERT INTO BANCOS VALUES('BANCO DO BRASIL',NULL,4,453380);
INSERT INTO BANCOS VALUES('ITAU',NULL,1,980130);
INSERT INTO BANCOS VALUES('SANTANDER',NULL,3,770710);
INSERT INTO BANCOS VALUES('ITAU',NULL,1,985001);
INSERT INTO BANCOS VALUES('SANTANDER',NULL,3,985002);
INSERT INTO BANCOS VALUES('ITAU',NULL,1,888132);


SELECT C.NOME,C.IDNUMERO,C.VALOR,C.VENCIMENTO,B.NOME,B.IDBANCO,B.ID_REGISTROB
FROM CONTAS C
INNER JOIN BANCOS B
ON C.IDNUMERO = B.ID_NUMERO;

1. Listar nome,vencimento e valor de cada duplicata da tabela. 

SELECT NOME, VENCIMENTO, VALOR
FROM CONTAS;

2. Apresentar o número das duplicatas depositadas no banco Itaú 
SELECT IDBANCO, COUNT(*)
FROM BANCOS
WHERE IDBANCO = 1;

4.Quais são as duplicatas (número, vencimento, valor e nome) que vencem no ano de 2017. 
SELECT , NOME, VALOR, VENCIMENTO,IDNUMERO
FROM CONTAS
WHERE VENCIMENTO LIKE '2017%';

5.Apresentar as duplicatas (número, vencimento, valor e nome) que não estão depositadas nos bancos Itaú e
Santander. 

--TIRAR 1 E 3

SELECT C.NOME,C.VALOR,C.VENCIMENTO,C.IDNUMERO,B.IDBANCO
FROM CONTAS C
INNER JOIN BANCOS B
ON C.IDNUMERO = B.ID_NUMERO
WHERE IDBANCO = 4
OR
IDBANCO = 2;
-------------CONTANDO O NUMERO DE REGISTROS PRA CADA ID DO BANCO
SELECT COUNT(*), IDBANCO
FROM BANCOS
WHERE IDBANCO = 2
OR
IDBANCO = 4
GROUP BY IDBANCO;


6.Quanto é o valor da divida o cliente PAPELARIA SILVA, e quais são as duplicatas?
SELECT NOME, VALOR, VENCIMENTO, IDNUMERO
FROM CONTAS
WHERE NOME = 'PAPELARIA SILVA'
---SOMA DO VALOR TOTAL-------------
SELECT NOME, SUM(VALOR) AS 'TOTAL DO VALOR A SER SOMADO', VENCIMENTO, IDNUMERO
FROM CONTAS
WHERE NOME = 'PAPELARIA SILVA';

7.Retirar da tabela a duplicata 770710 do cliente LIVRARIA FERNANDES, por ter sido devidamente quitada. 
DELETE FROM CONTAS
WHERE
IDNUMERO = 770710;


8. Apresentar uma listagem em ordem alfabética por nome do cliente de todos os campos da tabela. 
SELECT C.IDNUMERO, C.NOME,C.VENCIMENTO,C.VALOR, B.ID_REGISTROB, B.IDBANCO,B.NOME
FROM CONTAS C
INNER JOIN BANCOS B
ON C.IDNUMERO = B.ID_NUMERO
ORDER BY C.NOME;

9. Apresentar uma listagem em ordem de data de vencimento com o nome do cliente, banco, valor e vencimento. 
SELECT C.IDNUMERO, C.NOME, C.VENCIMENTO, C.VALOR, B.ID_REGISTROB, B.IDBANCO, B.NOME
FROM CONTAS C
INNER JOIN BANCOS B
ON C.IDNUMERO = B.ID_NUMERO
ORDER BY C.VENCIMENTO;

10. As duplicatas do Banco do Brasil foram transferidas para o Santander. Proceder o ajuste dos registros.

UPDATE BANCOS
SET NOME = 'SANTANDER'
WHERE NOME LIKE 'BANCO%';

UPDATE BANCOS
SET IDBANCO = 3
WHERE IDBANCO = 4;

11. Quais são os clientes que possuem suas duplicatas depositadas no Banco Bradesco? 
SELECT C.NOME,B.IDBANCO
FROM CONTAS C
INNER JOIN BANCOS B
ON C.IDNUMERO = B.ID_NUMERO
WHERE B.IDBANCO = 2;

12. Qual é a previsão de recebimento no período de 01/01/2016 até 31/12/2016?
SELECT SUM(VALOR) AS 'VALOR TOTAL'
FROM CONTAS
WHERE VENCIMENTO LIKE '2016%';

13. Quanto a empresa tem para receber no período de 01/08/2016 até 30/08/2016?
SELECT SUM(VALOR) AS 'VALOR TOTAL'
FROM CONTAS
WHERE VENCIMENTO LIKE '2016/08'

14. Quais foram os itens adquiridos pelo cliente ABC PAPELARIA? 
SELECT NOME, IDNUMERO, VALOR
FROM CONTAS
WHERE NOME LIKE 'ABC PAPELARIA%';

15.Acrescentar uma multa de 15% para todos os títulos que se encontram vencidos no período de 01/01/2016 até
31/12/2016. 
SELECT (SUM(VALOR) * 0.15 +SUM(VALOR)) AS 'VALOR TOTAL COM MULTA'
FROM CONTAS
WHERE VENCIMENTO LIKE '2016%';

SELECT (VALOR * 0.15 + VALOR) AS 'VALORES COM MULTA'
FROM CONTAS
WHERE VENCIMENTO LIKE '2016%';

Acrescentar uma multa de 5% para todos os títulos vencidos entre 01/01/2017 e 31/05/2017 que sejam do
cliente LER E SABER

SELECT (VALOR * 0.05) AS 'MULTA APÓS VENCIMENTO', NOME, VENCIMENTO
FROM CONTAS
WHERE VENCIMENTO BETWEEN 20170101 AND 20170531
AND
NOME = 'LER E SABER';

17. Qual é a média aritmética dos valores das duplicatas do ano de 2016? 

SELECT TRUNCATE(AVG(VALOR),2) AS 'MEDIA DO ANO 2016'
FROM CONTAS
WHERE VENCIMENTO BETWEEN 20160101 AND 20161230;

18. Exiba as duplicatas e nome dos respectivos clientes que possuem duplicatas com valor superior a 10000,00? 
SELECT VALOR, NOME
FROM CONTAS
WHERE VALOR > 10000;

19. Qual o valor total das duplicatas lançadas para o banco Santander? 
SELECT COUNT(*) AS 'Numero de clientes',SUM(C.VALOR) as 'SOMA TOTAL', B.IDBANCO, B.NOME
FROM CONTAS C
INNER JOIN BANCOS B
ON C.IDNUMERO = B.ID_NUMERO
WHERE B.NOME = 'SANTANDER';

20. Quais são os clientes que possuem suas duplicatas depositadas nos Bancos Bradesco ou Itaú?
SELECT COUNT(*), NOME
FROM BANCOS           --- VERIFICAR A ORDEM DO OR
GROUP BY NOME;


SELECT C.NOME, B.IDBANCO, B.NOME
FROM CONTAS C
INNER JOIN BANCOS B
ON C.IDNUMERO = B.ID_NUMERO
WHERE B.IDBANCO = 1
OR
B.IDBANCO = 2
ORDER BY B.NOME;
